#!/usr/bin/env ruby
# Date: 20140105_125300
# "query word from youdao"

require 'net/http'
require 'json'

def query(word)
        #if RUBY_PLATFORM.include?("darwin")
        #        Thread.new do
        #                system "say #{word}"
        #        end
        #end

        red = "\e[1m\e[31m"
        green = "\e[1m\e[32m"
        nocolor = "\e[0m"

        base_url = 'http://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule&smartresult=ugc&sessionFrom=dict.top'
        uri = URI base_url
        response = Net::HTTP.post_form(uri, 'type' => 'AUTO', 'i' => word, 'doctype' => 'json', 'xmlVersion' => '1.4', 'keyfrom' => 'fanyi.web', 'ue' => 'UTF-8', 'typoResult' => 'true', 'flag' => 'false')

        json = JSON.parse(response.body.gsub(' ', '').force_encoding(Encoding::UTF_8))
        #puts "json => #{json}"

        tgt = json["translateResult"][0][0]["tgt"]
        desc = json["smartResult"]["entries"]

        puts "[#{red}#{tgt}#{nocolor}]"
        desc.each { |line| puts "#{green}#{line}#{nocolor}" if line.length > 0 }
end

if $0 == __FILE__
        if ARGV.length < 1
                puts "Usage: ts word" 
                exit 1
        end

        ARGV.each { |word| query(word) }
end
