(defun getpid ()
  #+clisp (os:process-id)
  #+(or cmu scl) (unix:unix-getpid)
  #+sbcl (sb-unix:unix-getpid)
  #+gcl (system:getpid)
  #+openmcl (ccl::getpid)
  #+lispworks (system::getpid)
  #+(or ecl mkcl) (si:getpid)
  #+ccl (ccl::getpid)
  #-(or clisp cmu scl sbcl gcl openmcl lispworks ecl ccl mkcl) (getpid-from-environment))
